In [27]:
#Numpy:
#convert matrix into numpy array:
import numpy as np
M= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [84]:
#Slicing to pull out subarray of 2*2:
b= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b[:2,:2]

array([[1, 2],
       [5, 6]])

In [71]:
#create an empty matrix:
y= np.empty((0,4))
y

array([], shape=(0, 4), dtype=float64)

In [77]:
#add vector z to each col:
import numpy as np
M=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
z=np.array([1,0,1])
for i in range(4):
    y[i,:]= M[i,:]+z
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [49]:
#given:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
v=np.array([9,10])
#Add matrices:
s=np.add(A,B)
print("sum of A,B is\n",s)
#multiply matrices:
m=np.dot(A,B)
print("Multiplication of A,B is:\n",m)
#Square roor of A:
sq=np.sqrt(A)
print("Square root of A is:\n", sq)
#Dot product of A and v:
print("Dot product of Aand v is:")
print(A.dot(v))
#sum of each col of A:
s=np.sum(A,axis=0)
print("Sum of each col of A:")
print(s)
#Transpose of matrix B:
print("Transpose of a matix B is:\n",np.transpose(B))

sum of A,B is
 [[ 6  8]
 [10 12]]
Multiplication of A,B is:
 [[19 22]
 [43 50]]
Square root of A is:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Dot product of Aand v is:
[29 67]
Sum of each col of A:
[4 6]
Transpose of a matix B is:
 [[5 7]
 [6 8]]
